### ISSUE TITLE
installing with composer issues

### ISSUE THREAD

**Issue by llbbl** [eelkevdbos/firebase-php#13]
$ composer require eelkevdbos/firebase-php
Using version 0.1.* for eelkevdbos/firebase-php
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
```
    - eelkevdbos/firebase-php v0.1.2 requires guzzlehttp/guzzle 4.1.1 -> no matching package found.
    - eelkevdbos/firebase-php v0.1.1 requires guzzlehttp/guzzle dev-master#d79c982 -> no matching package found.
    - eelkevdbos/firebase-php v0.1 requires guzzlehttp/guzzle dev-master#d79c982 -> no matching package found.
    - Installation request for eelkevdbos/firebase-php 0.1.* -> satisfiable by eelkevdbos/firebase-php[v0.1, v0.1.1, v0.1.2].
```

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**then tried with dev-master:**

$composer require eelkevdbos/firebase-php dev-master
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
```
    - Installation request for eelkevdbos/firebase-php dev-master -> satisfiable by eelkevdbos/firebase-php[dev-master].
    - eelkevdbos/firebase-php dev-master requires firebase/php-jwt ~1.0 -> no matching package found.
```

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <http://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Composer.json**
```
{
    "require": {
        "illuminate/support": "~4.0",
        "firebase/php-jwt": "dev-master",
        "guzzlehttp/guzzle": "~5.0.3"
    }
}
```

**Comment by llbbl** [comment]
tried changing firebase/php-jwt .. to a couple different things to get it working... 

think its the composer.json for this project.  can't find the right dependance for firebase/php-jwt

**Comment by llbbl** [comment]
Also can you update guzzle to ~5.2 when possible please.

**Comment by eelkevdbos** [comment]
The dependency on guzzle version is now set to 5.*
If your problems persist, please open a new issue.

**Comment by llbbl** [comment]
thanks @eelkevdbos

**Comment by hopeseekr** [comment]
Logan, did you ever resolve this issue? When I run composer update on an almost identical composer.json, I receive the same error...

    - The requested package firebase/php-jwt dev-master could not be found.
