### ISSUE TITLE
question about event

### ISSUE THREAD

**Issue by cmosguy** [eelkevdbos/firebase-php#14]
Hi @eelkevdbos,

Is it it possible with your php code to trigger on an event when the firebase is update.  For example, I have a JS client that updates data in the firebase on the server.  The PHP code that you have is also a client, but is there a channel that is opened to the firebase server that will pick up the new update?  I am trying to understand how this works on the backend.  Do I have to write php code that polls the firebase server loop?

Thanks!
Adam

**Comment by eelkevdbos** [comment]
Hi @cmosguy,

The current version of the library doesn't support a server-loop that sends streaming updates. I've experimented with this feature for a bit, but had to conclude there are far more suitable solutions for this problem in other languages (nodejs for example). 

To enable your js application to get 'realtime' notifications with the current version of my firebase wrapper you could implement some long-polling mechanism, but then again, this would hurt the service more than you gain in user experience.

Cheers,

Eelke
