### ISSUE TITLE
Advance Queries

### ISSUE THREAD

**Issue by jokerxvier** [eelkevdbos/firebase-php#15]
Hi,
Just want to know if how can I used the orderBy and startAt in $fb->get()?

**Comment by michaeldim** [comment]
Something like this should work. Just make sure you define the keys you use in the .indexOn rule in security rules.

``` php
return $fb->get('event', new Criteria('expiry', [ 'startAt' => 1439986255, [ 'limitToFirst' => 1 ] ]));
});
```

**Comment by jokerxvier** [comment]
i tried the code above but it's returning an error. 

Client error response [url] https://firebaseio.com/Store.json?startAt=enable&limitToFirst=1&orderBy=%22status%22&auth=LDtn2beWZjEq3cmhXVnUBPh7gUI7KRJ6BpEIzqSQ [status code] 400 [reason phrase] Bad Request

**Comment by michaeldim** [comment]
You haven't set status as your index on your security rules. You need to add something like:

```
  "rules": {
      "store": {
      ".indexOn": "status"
      },...
```

_"If you're using orderBy="$value" in your app, you need to add .value to your rules at the appropriate index. Read the documentation on the .indexOn rule for more information."_

https://www.firebase.com/docs/security/guide/indexing-data.html.

**You now might want to change your auth token in your app as you have pasted it within your query in the last post!**

**Comment by michaeldim** [comment]
you need to pass startAt value within parenthesis as well,

startAt="enable"

**Comment by jokerxvier** [comment]
closing this issue. the issue has been solved.

**Comment by serneelsalexis** [comment]
Hi.

In your example. Where does the "Criteria" class come from?

How to achieve queries with this library?
Thanks.

**Comment by AlexisSerneels** [comment]
Hi.

For info, if passing a string in the delimiter such as `equalTo`, it's needed to add double quotes.
Such as : `new \Firebase\Criteria('status', [ 'equalTo' => '"accepted"' ]));`

By default the `orderBy` parameter gets double quotes, not the  `params`.
