### ISSUE TITLE
URI Parameters

### ISSUE THREAD

**Issue by AlexisSerneels** [eelkevdbos/firebase-php#18]
Current get() function only accepts a Criteria as parameter.
We need to be able to use any of the URI Parameters listed here: https://www.firebase.com/docs/rest/guide/retrieving-data.html#section-rest-uri-params such as 'shallow' or 'print'.

Regards,

**Comment by serneelsalexis** [comment]
PR submitted: https://github.com/eelkevdbos/firebase-php/pull/19

**Comment by AlexisSerneels** [comment]
PR submitted: https://github.com/eelkevdbos/firebase-php/pull/19

**Comment by adamontherun** [comment]
@eelkevdbos this would be really helpful. is this something you plan on incorporating?

**Comment by eelkevdbos** [comment]
Hi @serneelsalexis, @adamontherun, the second parameter of the Criteria constructor allows you to supply an array of request parameters. Sorry for the delay in answering. Does this solve your problem?

**Comment by adamontherun** [comment]
thx @eelkevdbos much appreciated.
