### ISSUE TITLE
Laravel 5.2 Error creating resource

### ISSUE THREAD

**Issue by simkepal** [eelkevdbos/firebase-php#20]
Hello,

I want to use laravel 5.2 with firebase. When I try to get data from firebase I get this error. Can you please help me with this? Thank you!

Code: 
` $hash = $request->get('hash');

 $fb = Firebase::initialize('https://dasdsadas.firebaseio.com', 'dasdasdasdasdas');

$nodeGetContent = $fb->get('/users/' . $hash);

dd($nodeGetContent);`

ERROR:
RequestException in RequestException.php line 51:
Error creating resource: [message] fopen(https://dasdsadas.firebaseio.com/users/dsadsada.json?auth=dasdasdasdasdas): failed to open stream: Connection timed out
[file] /var/www/getaride-api/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 406
[message] Undefined variable: http_response_header
[file] /var/www/getaride-api/vendor/guzzlehttp/ringphp/src/Client/StreamHandler.php
[line] 407

**Comment by sentiasa** [comment]
@simkepal I'm experiencing the exact same issue and couldn't figure out what's causing it. Did you manage to solve the issue? I'd be grateful if you can help.. Thanks
